name: "Build workflows container"
on:
  workflow_dispatch: {}
  push:
    branches:
      - "workflow-cache-docker-image"

jobs:
  build:
    name: "Build workflows container"
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: "ghcr.io/david-lor/spotify-playlist-github-workflows:latest"

    steps:
      - name: "Checkout"
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: "Login into ghcr"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Docker build"
        run: docker build . -f .github/workflows/container_build/Dockerfile -t ${IMAGE_TAG}
      - name: "Docker push into ghcr"
        run: docker push ${IMAGE_TAG}
