name: "Export playlist chart"
on:
  workflow_dispatch: {}
  #schedule:
  #  - cron: "0 6 * * *"  # daily at 6am

jobs:
  playlistChart:
    name: "Export Spotify Playlist statistics chart and commit on repository"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: "Setup Python"
        uses: actions/setup-python@master
        with:
          python-version: "3.8"
          architecture: "x64"
      - name: "Cache pip"
        uses: actions/cache@v2
        with:
          path: "~/.cache/pip"
          key: "playlist_chart-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements.plotly.txt') }}"
      - name: "Install Python requirements"
        run: pip install --upgrade-strategy eager -r spotify_client/requirements.txt -r spotify_client/requirements.plotly.txt
      - name: "Export stats"
        run: python run_spotify_client.py export_stats
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          SPOTIFY_PLAYLIST_ID: ${{ secrets.SPOTIFY_PLAYLIST_ID }}
          PLAYLIST_STATS_FILE: playlist_stats.ndjson
      - name: "Export chart"
        run: python run_spotify_client.py export_chart
        env:
          PLAYLIST_STATS_FILE: playlist_stats.ndjson
          PLAYLIST_CHART_FILE: playlist_chart.svg
      - name: Git Commit & Push
        uses: EndBug/add-and-commit@v7
        with:
          add: "playlist_stats.ndjson playlist_chart.svg"
          message: "Export playlist stats & chart"
          push: true
