name: "Pull Playlist"
on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 4 * * *"  # daily at 4am
  push:
    branches:
      - "workflow-cache-docker-image"

jobs:
  playlistPull:
    name: "Pull Spotify Playlist and commit on repository"
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/david-lor/spotify-playlist-github-workflows"

    steps:
      - name: "Checkout"
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Run
        run: python run_spotify_client.py pull
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          SPOTIFY_PLAYLIST_ID: ${{ secrets.SPOTIFY_PLAYLIST_ID }}
          PLAYLIST_FILE: playlist.tsv
      - name: Git Commit & Push
        uses: EndBug/add-and-commit@v7
        with:
          add: "playlist.tsv"
          message: "Update playlist from Spotify"
          push: true
